const START_ADD_PERSON = "START_ADD_PERSON";
const SUCCESS_ADD_PERSON = "SUCCESS_ADD_PERSON";
const ERROR_ADD_PERSON = "ERROR_ADD_PERSON";
const CLEAR_PERSON_VALUES = "CLEAR_PERSON_VALUES"
export  {START_ADD_PERSON,SUCCESS_ADD_PERSON,ERROR_ADD_PERSON, CLEAR_PERSON_VALUES}